### ISSUE TITLE
dank unloader auto deleted

### ISSUE THREAD

**Issue by brasilcraft54** [Sefiraat/DankTech2#8] opened 2022-03-07 15:21 UTC
the dank unloader Machine is disappearing when the server restarts.

Purpur git-Purpur-"08dd6c7" (MC: 1.17.1)
Slimefun DEV - 999 (git e02eedd9)
Metrics-Module #28
Java 16

Installed Addons: (10)
  DankTech2 vDEV - 4 (git 803760fb)
  Networks vDEV - 31 (git 773a911c)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  CMILib v1.0.3.11
  ExtraTools vDEV - 33 (git 46d26e49)
  IllegalStack v2.4.2
  EcoPower vDEV - 5 (git 5c1ecd68)
  MobCapturer vDEV - 17 (git c21b00a5)
  HotbarPets vDEV - 38 (git fa6c871d)
  ExoticGarden vDEV - 78 (git 7f9a5f63)

**Comment by Sefiraat** [comment] 2022-03-07 15:22
Duplicate of #7

**Closed by Sefiraat** 2022-03-07 15:22 UTC
